name: daily-shotgun

on:
  schedule:
    - cron: "0 6 * * *"   # 06:00 UTC = 08:00 Paris
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          playwright install --with-deps chromium
          pip install gspread google-auth google-auth-oauthlib python-dotenv

      - name: Configure env
        env:
          GCP_SA_JSON: ${{ secrets.GCP_SA_JSON }}
        run: |
          set -euxo pipefail
          echo "${GCP_SA_JSON}" > "$RUNNER_TEMP/sa.json"
          echo "GOOGLE_APPLICATION_CREDENTIALS=$RUNNER_TEMP/sa.json" >> $GITHUB_ENV

      - name: Diag (env + import + sheets)
        env:
          SHOTGUN_EMAIL: ${{ secrets.SHOTGUN_EMAIL }}
          SHOTGUN_PASSWORD: ${{ secrets.SHOTGUN_PASSWORD }}
          GSHEET_ID: ${{ secrets.GSHEET_ID }}
          GSHEET_DOC_TITLE: "Concerts Pointages"
          GSHEET_WORKSHEET: "shotgun_events"
          GOOGLE_APPLICATION_CREDENTIALS: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
          python .github/scripts/diag.py

      - name: Run ETL
        if: success()   # n'exécute que si la DIAG passe
        env:
          SHOTGUN_EMAIL: ${{ secrets.SHOTGUN_EMAIL }}
          SHOTGUN_PASSWORD: ${{ secrets.SHOTGUN_PASSWORD }}
          GSHEET_ID: ${{ secrets.GSHEET_ID }}
          GSHEET_DOC_TITLE: "Concerts Pointages"
          GSHEET_WORKSHEET: "shotgun_events"
          GOOGLE_APPLICATION_CREDENTIALS: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
          python -m concerts_etl run || (echo "ETL failed, dumping debug" && exit 1)

      - name: Upload exports (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: exports
          path: exports
          if-no-files-found: ignore
