name: daily-shotgun

on:
  schedule:
    - cron: "0 6 * * *"   # 06:00 UTC = 08:00 Europe/Paris
  workflow_dispatch: {}   # permet de lancer à la main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      # --- Checkout code ---
      - uses: actions/checkout@v4

      # --- Python 3.11 ---
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # --- Dépendances ---
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          playwright install --with-deps chromium
          pip install gspread google-auth google-auth-oauthlib python-dotenv

      # --- Config secrets (Service Account JSON) ---
      - name: Configure env
        env:
          GCP_SA_JSON: ${{ secrets.GCP_SA_JSON }}
        run: |
          echo "${GCP_SA_JSON}" > "$RUNNER_TEMP/sa.json"
          echo "GOOGLE_APPLICATION_CREDENTIALS=$RUNNER_TEMP/sa.json" >> $GITHUB_ENV

      # --- Diag step (facultatif mais utile) ---
      - name: Diag env
        run: |
          echo "Python $(python --version)"
          ls -lh $GOOGLE_APPLICATION_CREDENTIALS || true
          head -n 5 $GOOGLE_APPLICATION_CREDENTIALS || true

      # --- Run ETL ---
      - name: Run ETL
        env:
          SHOTGUN_EMAIL: ${{ secrets.SHOTGUN_EMAIL }}
          SHOTGUN_PASSWORD: ${{ secrets.SHOTGUN_PASSWORD }}
          DICE_EMAIL: ${{ secrets.DICE_EMAIL }}
          DICE_PASSWORD: ${{ secrets.DICE_PASSWORD }}
          GSHEET_ID: ${{ secrets.GSHEET_ID }}
          GSHEET_DOC_TITLE: "Concerts Pointages"
          GSHEET_WORKSHEET: "shotgun_events"
          GOOGLE_APPLICATION_CREDENTIALS: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
          python -m concerts_etl run

      # --- Debug login (si échec login) ---
      - name: Upload login debug
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: login-debug
          path: |
            login_error.png
            login_error.html
          if-no-files-found: ignore

      # --- Debug events (si aucune donnée) ---
      - name: Upload events debug
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: events-debug
          path: |
            events.html
            events_empty.png
          if-no-files-found: ignore

      - name: Upload Dice debug
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dice-debug
          path: |
            dice_cards_count.txt
            dice_diag.txt
            dice_events_preview.json
            events_error.html
            events_error.png
          if-no-files-found: ignore

      - name: Upload providers preview
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: providers-preview
          path: providers_preview.json
          if-no-files-found: ignore


      # --- Export CSV (optionnel) ---
      - name: Upload CSV exports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: csv-exports
          path: exports
          if-no-files-found: ignore
